Reapply corrections to various models
zhanglab/psamm-model-collection pull request #5
Opened 2017-03-23 19:02 UTC by ssuchacz

2017-03-29 18:36 UTC, keithdt reviewed
The only needed change i saw was the compound designation for biomass in the iMA871 model.

2017-03-29 18:36 UTC, keitht547 commented on sbml/iMA871/exchange.yaml
> +  compartment: C-c
Can we double check the formatting of this and make sure that the compartment designation is correct. Its usually C_c not C-c

2017-03-29 18:36 UTC, keitht547 commented on sbml/iMA871/exchange.yaml
> +  compartment: C-c
Also now the compartment should just be 'c' not with the C_c due to the improvements to PSAMM-import parsing.

2017-03-29 18:51 UTC, jonls requested changes

2017-03-29 18:51 UTC, jonls commented on sbml/RECON1/reactions.yaml
> +  equation: M_2kmb[c] + M_gln__L[c] + (2) M_h_c[c] => M_glu__L[c] + M_met__L[c]
@ssuchacz I think the `M_` prefix, and on `M_h_c` the `_c` suffix, should not be added. These prefixes/suffixes are no longer part of the model so your change should not reintroduce them. The change here should just be to add the additional `h[c]`.

2017-03-29 18:58 UTC, jonls commented
@ssuchacz Keith noticed that you had applied the changes to the iSyn731 from the commit I specified. Those changes were not actually manual corrections but were just a result of importing the model from a newer file. It looks like the changes you made were correct but a better/safer way to do this was to simply reimport the correct model file. I'm sorry I didn't notice this earlier. I have reimported iSyn731 from the correct file now so that is why it says that your branch has conflicts. You can ignore this message for now.

2017-04-04 19:57 UTC, jonls reviewed
This looks good now. It would be nice if we could split this into separate commits, one for each model. This would then allow us to refer to specific commits for each model in the README file. You can ask me later if you don't know how to do this.

2017-04-06 19:31 UTC, closed without merging